In [1]:
import numpy as np

In [2]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,1])

In [3]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
y

array([0, 1, 1, 1])

In [6]:
w = np.array([1,1])

In [7]:
w

array([1, 1])

In [8]:
b = -0.5

In [16]:
pred = []
for a in x:
  y_hat = np.dot(a,w)+b
  pred.append(activation(y_hat))

In [17]:
pred

[0, 1, 1, 1]

In [15]:
def activation(z):
  if z >= 0:
    return 1
  else:
    return 0

### Perceptron Learning Concept:
Train weights over epochs and iterate prediction error back to the perceptron for each epoch.

During the error propagation process, we will make changes in our weight values till the time our perceptron makes accurate predictions.

Weight(new) = Weight(old) - Learning rate (Alpha) * (Gradient of error with respect to weight)

Error = output - predicted_output

In [18]:
import math
import numpy as np

In [19]:
epochs = 100
alpha = 0.2

In [20]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()
print("Initial Weights")
print("w0 =",w0,"w1 =",w1,"w2 =",w2)


Initial Weights
w0 = 0.9383203786836829 w1 = 0.6377835219365191 w2 = 0.5864364527440433


In [21]:
del_w0 = 1
del_w1 = 1
del_w2 = 1

In [24]:
train_data_temp = [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
train_data = np.asarray(train_data_temp)
op = np.array([0,1,1,1,1,1,1,1])

In [25]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [26]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

Y = (X*W) + b

In [29]:
bias = 0
for i in range(epochs):
  j = 0
  for x in train_data:
    y_hat = w0*x[0] + w1*x[1] + w2*x[2] + bias

    if(y_hat > 0):
      act = 1
    else:
      act = 0

    err = op[j] - act

    del_w0 = alpha*x[0]*err
    del_w1 = alpha*x[1]*err
    del_w2 = alpha*x[2]*err

    w0 = w0 + del_w0
    w1 = w1 + del_w1
    w2 = w2 + del_w2

    j = j+1
    print("epoch", i + 1, "Error =", err)
    print(del_w0,del_w1,del_w2)

print("\n Final Weights:")
print("w0 =",w0,"w1 =",w1,"w2 =",w2)




epoch 1 Error = 0
0.0 0.0 0.0
epoch 1 Error = 0
0.0 0.0 0.0
epoch 1 Error = 0
0.0 0.0 0.0
epoch 1 Error = 0
0.0 0.0 0.0
epoch 1 Error = 0
0.0 0.0 0.0
epoch 1 Error = 0
0.0 0.0 0.0
epoch 1 Error = 0
0.0 0.0 0.0
epoch 1 Error = 0
0.0 0.0 0.0
epoch 2 Error = 0
0.0 0.0 0.0
epoch 2 Error = 0
0.0 0.0 0.0
epoch 2 Error = 0
0.0 0.0 0.0
epoch 2 Error = 0
0.0 0.0 0.0
epoch 2 Error = 0
0.0 0.0 0.0
epoch 2 Error = 0
0.0 0.0 0.0
epoch 2 Error = 0
0.0 0.0 0.0
epoch 2 Error = 0
0.0 0.0 0.0
epoch 3 Error = 0
0.0 0.0 0.0
epoch 3 Error = 0
0.0 0.0 0.0
epoch 3 Error = 0
0.0 0.0 0.0
epoch 3 Error = 0
0.0 0.0 0.0
epoch 3 Error = 0
0.0 0.0 0.0
epoch 3 Error = 0
0.0 0.0 0.0
epoch 3 Error = 0
0.0 0.0 0.0
epoch 3 Error = 0
0.0 0.0 0.0
epoch 4 Error = 0
0.0 0.0 0.0
epoch 4 Error = 0
0.0 0.0 0.0
epoch 4 Error = 0
0.0 0.0 0.0
epoch 4 Error = 0
0.0 0.0 0.0
epoch 4 Error = 0
0.0 0.0 0.0
epoch 4 Error = 0
0.0 0.0 0.0
epoch 4 Error = 0
0.0 0.0 0.0
epoch 4 Error = 0
0.0 0.0 0.0
epoch 5 Error = 0
0.0 0.0 0.0
epoch 5 Er